/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beam.scottygui.TwitterInfo;

import static beam.scottygui.Stores.CentralStore.AuthKey;
import beam.scottygui.Utils.HTTP;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author tjhasty
 */
public class TwitterAuthInfo extends javax.swing.JFrame {

    /**
     * Creates new form TwitterAuthInfo
     */
    public TwitterAuthInfo() {
        initComponents();
        JSONObject ToParse = new JSONObject();
        String authinfo = "";
        try {
            String toSend = "https://api.scottybot.net/twitterauth?authkey=" + URLEncoder.encode(AuthKey, "UTF-8");
            System.err.println(toSend);
            authinfo = new HTTP().BeamGet(toSend);

        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(TwitterAuthInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ToParse.putAll((JSONObject) new JSONParser().parse(authinfo));
        } catch (ParseException ex) {
            Logger.getLogger(TwitterAuthInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.CKey.setText((String) ToParse.get("CKey"));
        this.CSecret.setText((String) ToParse.get("CSecret"));
        this.AToken.setText((String) ToParse.get("AToken"));
        this.ATokenSecret.setText((String) ToParse.get("ATokenSecret"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CKey = new javax.swing.JTextField();
        CSecret = new javax.swing.JTextField();
        AToken = new javax.swing.JTextField();
        ATokenSecret = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CKeyActionPerformed(evt);
            }
        });
        getContentPane().add(CKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 380, -1));

        CSecret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSecretActionPerformed(evt);
            }
        });
        getContentPane().add(CSecret, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 380, -1));
        getContentPane().add(AToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 380, -1));
        getContentPane().add(ATokenSecret, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 380, -1));

        jLabel1.setText("Twitter Authentication Information");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel2.setText("Check for HowTo link on Scottybot's Page");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 230, -1));

        jLabel3.setText("Consumer Key");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel4.setText("Consumer Secret");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel5.setText("Access Token");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel6.setText("Access Token Secret");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CKeyActionPerformed

    private void CSecretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSecretActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CSecretActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.CKey.getText() == null || this.CSecret.getText() == null || this.AToken.getText() == null || this.ATokenSecret.getText() == null) {
            JOptionPane.showMessageDialog(rootPane, "1 or more fields are incorrect.");
            return;
        }
        System.err.println("Got here 1");

        JSONObject AuthInfo = new JSONObject();
        System.err.println("Got here 2");
        try {
            String ckey = CKey.getText().trim();
            String csecret = CSecret.getText().trim();
            String atoken = AToken.getText().trim();
            String atokensecret = ATokenSecret.getText().trim();
            System.err.println("Got here 3");
            AuthInfo.put("ckey", ckey);
            AuthInfo.put("csecret", csecret);
            AuthInfo.put("atoken", atoken);
            AuthInfo.put("atokensecret", atokensecret);
            System.err.println("Got here 4");
        } catch (Exception e) {
            System.err.println(e);
        }
        System.err.println("Got here 5");
        try {
            String ToSend = "https://api.scottybot.net/twitterauth/add?authkey=" + URLEncoder.encode(AuthKey, "UTF-8") + "&twitterauth=" + URLEncoder.encode(AuthInfo.toString(), "UTF-8");
            new HTTP().GetScotty(ToSend);

        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(TwitterAuthInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.err.println("Got here 6");
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwitterAuthInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwitterAuthInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwitterAuthInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwitterAuthInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TwitterAuthInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AToken;
    private javax.swing.JTextField ATokenSecret;
    private javax.swing.JTextField CKey;
    private javax.swing.JTextField CSecret;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
