/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beam.scottygui.Alerts;

import static beam.scottygui.Stores.CentralStore.ChanID;
import static beam.scottygui.Stores.CentralStore.GUISettings;
import beam.scottygui.Utils.HTTP;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author tjhasty
 */
public final class AlertFrame extends javax.swing.JFrame {

    public List<String> FollowerCache = new ArrayList();
    public JSONParser parser = new JSONParser();
    HTTP http = new HTTP();
    boolean PlayingAudio = false;
    boolean ShowingImg = false;

    /**
     * Creates new form AlertFrame
     */
    public AlertFrame() {
        initComponents();
        StartFollowerWatcher();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AlertBG = new javax.swing.JPanel();
        ImageViewer = new javax.swing.JLabel();
        AlertMSG = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alert Pane");
        setResizable(false);

        AlertBG.setBackground(new java.awt.Color(51, 255, 51));

        AlertMSG.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        AlertMSG.setForeground(new java.awt.Color(255, 51, 51));
        AlertMSG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AlertMSG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AlertMSG.setDoubleBuffered(true);
        AlertMSG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout AlertBGLayout = new javax.swing.GroupLayout(AlertBG);
        AlertBG.setLayout(AlertBGLayout);
        AlertBGLayout.setHorizontalGroup(
            AlertBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlertBGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlertBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AlertMSG, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .addComponent(ImageViewer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AlertBGLayout.setVerticalGroup(
            AlertBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlertBGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageViewer, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AlertMSG, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Test Followers");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AlertBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jButton1)
                .addContainerGap(450, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AlertBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void StartFollowerWatcher() {
        new Thread("Follow Watcher") {
            @Override
            public void run() {
                while (true) {
                    JSONArray Followers = null;
                    while (true) {
                        try {
                            Followers = (JSONArray) parser.parse(http.BeamGet("https://beam.pro/api/v1/channels/" + ChanID + "/follow"));
                            break;
                        } catch (ParseException ex) {
                            Logger.getLogger(AlertFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    if (FollowerCache.isEmpty()) {
                        for (Object t : Followers) {
                            JSONObject obj = (JSONObject) t;
                            String userid = obj.get("id").toString();
                            FollowerCache.add(userid);
                        }
                    }

                    for (Object t : Followers) {
                        JSONObject obj = (JSONObject) t;
                        String userid = obj.get("id").toString();
                        if (!FollowerCache.contains(userid)) {
                            FollowerCache.add(userid);
                            String User = obj.get("username").toString();
                            BeginAlert(User);
                            while (PlayingAudio || ShowingImg) {
                                try {
                                    Thread.sleep(100);
                                } catch (InterruptedException ex) {
                                    Logger.getLogger(AlertFrame.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        }
                    }
                    try {
                        Thread.sleep(15000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(AlertFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }

        }.start();
    }

    public void BeginAlert(String Follower) {
        this.StartAudio();
        this.StartImage(Follower);
    }

    public void StartAudio() {
        PlayingAudio = true;
        new Thread("Sound Alert!") {
            @Override
            public void run() {
                FileInputStream fis = null;
                try {
                    fis = new FileInputStream(GUISettings.get("FollowSound").toString());
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(AlertFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    Player playMP3 = new Player(fis);
                    playMP3.play();
                    PlayingAudio = false;
                } catch (JavaLayerException ex) {
                    Logger.getLogger(AlertFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }.start();
    }

    public void StartImage(final String Follower) {
        ShowingImg = true;
        new Thread("Visual Alert!") {
            @Override
            public void run() {
                String image = GUISettings.get("FollowIMG").toString();
                BufferedImage img = null;
                try {
                    img = ImageIO.read(new File(image));
                } catch (IOException e) {
                    e.printStackTrace();
                }

                Image dimg = null;
                if (img.getHeight() > img.getWidth()) {
                    dimg = img.getScaledInstance(-1, ImageViewer.getHeight(), Image.SCALE_SMOOTH);
                } else if (img.getWidth() > img.getHeight()) {
                    dimg = img.getScaledInstance(ImageViewer.getWidth(), -1, Image.SCALE_SMOOTH);
                } else {
                    dimg = img;
                }

                ImageIcon imageIcon = new ImageIcon(dimg);
                ImageViewer.setHorizontalAlignment(JLabel.CENTER);
                ImageViewer.setVerticalAlignment(JLabel.CENTER);
                ImageViewer.setIcon(imageIcon);
                String FollowMessage = GUISettings.get("FollowerMSG").toString().replace("(_follower_)", Follower);

                try {
                    AlertMSG.setText(FollowMessage);

                    Thread.sleep(10000);
                    AlertMSG.setText("");
                    ShowingImg = false;
                } catch (InterruptedException ex) {
                    Logger.getLogger(AlertFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                ImageViewer.setIcon(null);
            }
        }.start();
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (PlayingAudio || ShowingImg) {
            return;
        }
        this.BeginAlert("Test");

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlertFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AlertBG;
    private javax.swing.JLabel AlertMSG;
    private javax.swing.JLabel ImageViewer;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
